username = input("Как вас зовут? ")
print(f"Здравствуйте, {username}")
title = input("Введите заголовок заметки: ")
print(title)
content = input("Введите содержание заметки: ")
print(content)
status = input("Введите статус: ")
print(status)